### ISSUE TITLE
`quilt.mod.json` references incorrect class name(s), leading to crash

### ISSUE THREAD

**Issue by unilock** [TelepathicGrunt/FullStackWatchdog#2]
https://github.com/TelepathicGrunt/FullStackWatchdog/blob/4859b3b00c7c5d589c1640ebcc35d6d6938bf5fd/quilt/src/main/resources/quilt.mod.json#L22

That should be `com.telepathicgrunt.fullstackwatchdog.quilt.FullStackWatchdogQuilt`, I imagine, with the following `"modmenu"` line not being necessary at all.

**Comment by TelepathicGrunt** [comment]
Honestly, just use the fabric version on quilt. The quilt jars are pointless and will be deleted
